"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(a_eb$o1c3tu%f!7grj-9zhv@xo1ck2=y^0dc75$w_5^2bt4hb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [

    # OWN APPS
    'account',
    'changes',
    'clients',
    'clients_only',
    'data',
    'deposit',
    'envios',
    'home',
    'mobile_app',
    'places',
    'prices',
    'summaries',
    'tickets',
    'tracking',
    'transactions',

    # DJANGO
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    # REST FRAMEWORK
    'rest_framework',
    'rest_framework.authtoken',

    # THIRD PARTY
    'rest_framework_swagger',
    'django_extensions',
    'django_cleanup.apps.CleanupConfig',
    'request',
]

AUTH_USER_MODEL = 'account.Account'

rf = 'rest_framework'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        f'{rf}.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        f'{rf}.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': f'{rf}.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'request.middleware.RequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'mysite.middleware.forwarder.XForwardedForMiddleware',
    'mysite.middleware.timezones.TimezoneMiddleware',
    'mysite.middleware.password.HasToResetPasswordMiddleware',
]

REQUEST_BASE_URL = 'http://localhost:8000'

ROOT_URLCONF = 'mysite.urls'

APPEND_SLASH = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'sinergiadb',
        'USER': 'postgres',
        'PASSWORD': 'A5euBFju*$XR2&Ct',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

base_validation = "django.contrib.auth.password_validation."

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': f'{base_validation}UserAttributeSimilarityValidator',
    },
    {
        'NAME': f'{base_validation}MinimumLengthValidator',
    },
    {
        'NAME': f'{base_validation}CommonPasswordValidator',
    },
    {
        'NAME': f'{base_validation}NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')
TEMP = os.path.join(BASE_DIR, 'temp')


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"rich": {"datefmt": "[%X]"}},
    "handlers": {
        "console": {
            "class": "rich.logging.RichHandler",
            "formatter": "rich",
            "level": "DEBUG",
        }
    },
    "loggers": {"django": {"handlers": ["console"]}},
}


# PERMISSIONS LISTS
TRANSFER_IN_NAME_OF_OTHERS = ["Admins", "Level 1"]
DELIVER_IN_NAME_OF_OTHERS = ["Admins", "Level 1"]
ACCESS_EMPLOYEE_APP = ["Admins", "Level 1", "Level 2"]


DEFAULT_RESULTS_PER_PAGE = 50


DEFAULT_RESET_PASSWORD = "Cambiar123"


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'jcmacielhenning@gmail.com'
# EMAIL_HOST_PASSWORD = 'bkwivgnwbouskjer'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# noreply = '<noreply@sinergiamensajeria.com>'
# DEFAULT_FROM_EMAIL = f'Administración de SinergiaSoftware {noreply}'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_HOST_USER = 'no-reply@sinergiamensajeria.com'
EMAIL_HOST_PASSWORD = 'b#5wZFJ273j2g'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
# EMAIL_USE_TLS = True
noreply = '<no-reply@sinergiamensajeria.com>'
DEFAULT_FROM_EMAIL = f'Administración de SinergiaSoftware {noreply}'
