# Generated by Django 2.2.2 on 2022-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycode',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='flexcode',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código'),
        ),
    ]
