# Generated by Django 2.2.2 on 2022-03-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20220127_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycode',
            name='bulto_max_10k_price',
            field=models.DecimalField(decimal_places=2, default=700.0, max_digits=20, verbose_name='Precio Bulto hasta 10kg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycode',
            name='bulto_max_20k_price',
            field=models.DecimalField(decimal_places=2, default=900.0, max_digits=20, verbose_name='Precio Bulto hasta 20kg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycode',
            name='max_5k_price',
            field=models.DecimalField(decimal_places=2, default=480.0, max_digits=20, verbose_name='Precio hasta 5kg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycode',
            name='miniflete_price',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=20, verbose_name='Precio miniflete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycode',
            name='tramite_price',
            field=models.DecimalField(decimal_places=2, default=900.0, max_digits=20, verbose_name='Precio trámite'),
            preserve_default=False,
        ),
    ]
