# Generated by Django 2.2.2 on 2021-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20211006_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycode',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='flexcode',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Código'),
        ),
    ]
