# Generated by Django 2.2.2 on 2022-09-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20220309_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycode',
            name='camioneta_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Precio trámite'),
            preserve_default=False,
        ),
    ]
