# Generated by Django 2.2.2 on 2021-10-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20211009_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycode',
            options={'ordering': ['code'], 'verbose_name': 'Código de Mensajería', 'verbose_name_plural': 'Códigos de Mensajería'},
        ),
        migrations.AlterModelOptions(
            name='flexcode',
            options={'ordering': ['code'], 'verbose_name': 'Código de Flex', 'verbose_name_plural': 'Códigos de Flex'},
        ),
    ]
