# Generated by Django 2.2.2 on 2022-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_deliverycode_camioneta_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycode',
            name='camioneta_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio camioneta'),
        ),
    ]
