# Generated by Django 2.2.2 on 2021-10-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_historicaldeliverycode_historicalflexcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycode',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='flexcode',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicaldeliverycode',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalflexcode',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
    ]
