# Generated by Django 2.2.2 on 2022-01-21 20:44

import clients.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Razón social / Nombre fantasía')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Persona de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de teléfono')),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('contract', models.FileField(blank=True, null=True, upload_to=clients.models.upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'doc', 'docx'])], verbose_name='Contrato')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('is_for_flex', models.BooleanField(default=False, verbose_name='Es Flex')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Es Flex')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('partidos', models.ManyToManyField(blank=True, to='places.Partido', verbose_name='Partidos')),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
                'ordering': ['amount'],
            },
        ),
    ]
