# Generated by Django 2.2.2 on 2021-09-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='client name')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact name')),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact name')),
                ('discount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
