# Generated by Django 2.2.2 on 2022-01-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['amount'], 'verbose_name': 'descuento', 'verbose_name_plural': 'descuentos'},
        ),
    ]
