# Generated by Django 2.2.2 on 2022-03-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_for_flex',
            field=models.BooleanField(default=False, verbose_name='Es para envíos flex'),
        ),
    ]
