# Generated by Django 2.2.2 on 2021-11-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0021_auto_20211025_2034'),
        ('clients', '0002_historicalclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.CreateModel(
            name='HistoricalDeposit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_ours', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Client', verbose_name='client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Town')),
            ],
            options={
                'verbose_name': 'historical Depósito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_ours', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='client')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Town')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
    ]
