# Generated by Django 2.2.2 on 2022-01-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220105_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Es Flex'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_for_flex',
            field=models.BooleanField(default=False, verbose_name='Es Flex'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='partidos',
            field=models.ManyToManyField(blank=True, to='places.Partido', verbose_name='Partidos'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='towns',
            field=models.ManyToManyField(blank=True, to='places.Town', verbose_name='Localidades'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Client', verbose_name='Es Flex'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='is_for_flex',
            field=models.BooleanField(default=False, verbose_name='Es Flex'),
        ),
    ]
