# Generated by Django 2.2.2 on 2022-08-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220308_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo'),
        ),
    ]
