# Generated by Django 2.2.2 on 2022-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220116_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Razón social / Nombre fantasía'),
        ),
    ]
