# Generated by Django 2.2.2 on 2022-01-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20220105_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='towns',
        ),
    ]
