# Generated by Django 2.2.2 on 2021-11-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20211102_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='town',
        ),
        migrations.RemoveField(
            model_name='historicaldeposit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicaldeposit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldeposit',
            name='town',
        ),
    ]
