# Generated by Django 2.2.2 on 2022-01-05 13:58

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_discount_towns'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=clients.models.upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'doc', 'docx'])], verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='contract',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'doc', 'docx'])], verbose_name='Contrato'),
        ),
    ]
