# Generated by Django 2.2.2 on 2021-11-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20211102_1719'),
        ('envios', '0032_auto_20211102_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='HistoricalDeposit',
        ),
    ]
