# Generated by Django 2.2.2 on 2022-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20220105_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Razón social / Nombre fantasía'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Razón social / Nombre fantasía'),
        ),
    ]
