# Generated by Django 2.2.2 on 2022-01-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20220105_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'descuento', 'verbose_name_plural': 'descuentos'},
        ),
        migrations.AlterModelOptions(
            name='historicaldiscount',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical descuento'},
        ),
    ]
