# Generated by Django 2.2.2 on 2022-01-12 16:41

import account.models
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('can_distribute', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=account.models.profile_pic_upload_location, verbose_name='profile picture')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='dni')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('dni_img', models.ImageField(blank=True, null=True, upload_to=account.models.doc_upload_location, verbose_name='doc picture')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('employee1', 'Empleado 1'), ('employee2', 'Empleado 2')], default='employee2', max_length=9, verbose_name='Rol')),
                ('driver_license', models.FileField(blank=True, null=True, upload_to=account.models.driver_licence_upload_location, verbose_name='Licencia de conducir')),
                ('criminal_record', models.FileField(blank=True, null=True, upload_to=account.models.criminal_record_upload_location, verbose_name='Antecedentes penales')),
                ('vtv', models.FileField(blank=True, null=True, upload_to=account.models.vtv_upload_location, verbose_name='VTV')),
                ('insurance', models.FileField(blank=True, null=True, upload_to=account.models.insurance_upload_location, verbose_name='Seguro')),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('other', 'Otro')], max_length=10, null=True, verbose_name='Tipo de vehículo')),
                ('vehicle_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente')),
                ('has_to_reset_password', models.BooleanField(default=False, verbose_name='¿Tiene que resetear la contraseña?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='email')),
                ('username', models.CharField(db_index=True, max_length=40)),
                ('date_joined', models.DateTimeField(blank=True, editable=False, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, editable=False, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('can_distribute', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_picture', models.TextField(blank=True, max_length=100, null=True, verbose_name='profile picture')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('dni', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='dni')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('dni_img', models.TextField(blank=True, max_length=100, null=True, verbose_name='doc picture')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('employee1', 'Empleado 1'), ('employee2', 'Empleado 2')], default='employee2', max_length=9, verbose_name='Rol')),
                ('driver_license', models.TextField(blank=True, max_length=100, null=True, verbose_name='Licencia de conducir')),
                ('criminal_record', models.TextField(blank=True, max_length=100, null=True, verbose_name='Antecedentes penales')),
                ('vtv', models.TextField(blank=True, max_length=100, null=True, verbose_name='VTV')),
                ('insurance', models.TextField(blank=True, max_length=100, null=True, verbose_name='Seguro')),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('other', 'Otro')], max_length=10, null=True, verbose_name='Tipo de vehículo')),
                ('vehicle_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente')),
                ('has_to_reset_password', models.BooleanField(default=False, verbose_name='¿Tiene que resetear la contraseña?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
