# Generated by Django 2.2.2 on 2021-09-22 18:47

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dni_img',
            field=models.ImageField(blank=True, max_length=60, null=True, upload_to=account.models.doc_upload_location, verbose_name='doc picture'),
        ),
    ]
