# Generated by Django 2.2.2 on 2021-09-28 14:31

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_dni_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.profile_pic_upload_location, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dni_img',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.doc_upload_location, verbose_name='doc picture'),
        ),
    ]
