# Generated by Django 2.2.2 on 2022-01-07 10:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220103_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='criminal_record',
            field=models.FileField(blank=True, null=True, upload_to=account.models.criminal_record_upload_location, verbose_name='Antecedentes penales'),
        ),
        migrations.AddField(
            model_name='account',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to=account.models.driver_licence_upload_location, verbose_name='Licencia de conducir'),
        ),
        migrations.AddField(
            model_name='account',
            name='insurance',
            field=models.FileField(blank=True, null=True, upload_to=account.models.insurance_upload_location, verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('employee1', 'Empleado 1'), ('employee2', 'Empleado 2')], default='employee2', max_length=9, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='account',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='account',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('other', 'Otro')], default='car', max_length=10, null=True, verbose_name='Tipo de vehículo'),
        ),
        migrations.AddField(
            model_name='account',
            name='vtv',
            field=models.FileField(blank=True, null=True, upload_to=account.models.vtv_upload_location, verbose_name='VTV'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='criminal_record',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Antecedentes penales'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='driver_license',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Licencia de conducir'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='insurance',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('employee1', 'Empleado 1'), ('employee2', 'Empleado 2')], default='employee2', max_length=9, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('other', 'Otro')], default='car', max_length=10, null=True, verbose_name='Tipo de vehículo'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='vtv',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='VTV'),
        ),
    ]
