# Generated by Django 2.2.2 on 2022-01-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220114_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-username'], 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
