# Generated by Django 2.2.2 on 2022-01-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220107_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_to_reset_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='has_to_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
