# Generated by Django 2.2.2 on 2022-01-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220124_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-is_active', '-username'], 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
