# Generated by Django 2.2.2 on 2022-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220126_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['is_active', '-username'], 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('level 1', 'Nivel 1'), ('level 2', 'Nivel 2')], default='employee2', max_length=9, verbose_name='Rol'),
        ),
    ]
