# Generated by Django 2.2.2 on 2022-01-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220107_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='has_to_reset_password',
            field=models.BooleanField(default=False, verbose_name='¿Tiene que resetear la contraseña?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('other', 'Otro')], max_length=10, null=True, verbose_name='Tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='has_to_reset_password',
            field=models.BooleanField(default=False, verbose_name='¿Tiene que resetear la contraseña?'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('other', 'Otro')], max_length=10, null=True, verbose_name='Tipo de vehículo'),
        ),
    ]
