# Generated by Django 2.2.2 on 2021-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211030_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_distribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='can_distribute',
            field=models.BooleanField(default=False),
        ),
    ]
