# Generated by Django 2.2.2 on 2022-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220126_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('level_1', 'Nivel 1'), ('level_2', 'Nivel 2')], default='level_2', max_length=9, verbose_name='Rol'),
        ),
    ]
