# Generated by Django 2.2.2 on 2022-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220126_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_access_denied',
            field=models.BooleanField(default=False),
        ),
    ]
