# Generated by Django 2.2.2 on 2022-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_has_access_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='FCM Token'),
        ),
    ]
