# Generated by Django 2.2.2 on 2022-03-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fcm_token',
        ),
    ]
