# Generated by Django 2.2.2 on 2022-03-07 03:03

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to=account.models.cedula_upload_location, verbose_name='Cédula'),
        ),
    ]
