# Generated by Django 2.2.2 on 2022-03-07 11:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to=account.models.insurance_upload_location, verbose_name='Cédula'),
        ),
    ]
