# Generated by Django 2.2.2 on 2022-03-07 18:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220307_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dni_img',
            field=models.FileField(blank=True, null=True, upload_to=account.models.doc_upload_location, verbose_name='doc picture'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('level_1', 'Distribuidor + Repartidor'), ('level_2', 'Motoquero')], default='level_2', max_length=9, verbose_name='Rol'),
        ),
    ]
