# Generated by Django 2.2.2 on 2022-03-16 12:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220307_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to=account.models.cedula_upload_location, verbose_name='Cédula'),
        ),
    ]
