# Generated by Django 2.2.2 on 2022-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
