# Generated by Django 2.2.2 on 2022-04-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-created_at'], 'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
    ]
