# Generated by Django 2.2.2 on 2021-12-22 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLoadEnvios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('load_status', models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado')),
                ('csv_result', models.TextField(blank=True, default=None, null=True, verbose_name='Resultado')),
                ('errors', models.TextField(blank=True, default=None, null=True, verbose_name='Errores')),
                ('cells_to_paint', models.TextField(blank=True, default=None, null=True, verbose_name='Celdas que hay que pintar')),
                ('requires_manual_fix', models.BooleanField(default=False)),
                ('hashed_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hashed file')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client', verbose_name='Usuario')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Deposit', verbose_name='Depósito')),
            ],
            options={
                'verbose_name': 'Carga masiva de envios',
                'verbose_name_plural': 'Cargas masivas de envios',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Domicilio de entrega')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de entrega')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. Postal de entrega')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Town', verbose_name='Localidad de entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Subprueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('subprueba_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envios.Subprueba')),
                ('value', models.BooleanField(default=True)),
            ],
            bases=('envios.subprueba',),
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envios.Destination')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre destinatario')),
                ('doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI destinatario')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono destinatario')),
            ],
            bases=('envios.destination',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado')),
                ('carrier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_old_state', to=settings.AUTH_USER_MODEL, verbose_name='ID de carga masiva')),
                ('deposit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_old_state', to='places.Deposit', verbose_name='deposit')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTrackingMovement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('action', models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='movement action')),
                ('result', models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='comment')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name="action's date time")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('deposit', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Deposit', verbose_name='deposit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Movimiento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEnvio',
            fields=[
                ('receiver_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='envios.Receiver')),
                ('destination_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='envios.Destination')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Domicilio de entrega')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de entrega')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. Postal de entrega')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre destinatario')),
                ('doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI destinatario')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono destinatario')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('shipment_status', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado')),
                ('status_o', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado')),
                ('detail', models.CharField(default='0-1', max_length=2000, verbose_name='Detalle')),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Cargos al destinatario')),
                ('max_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha máxima de entrega')),
                ('is_flex', models.BooleanField(default=False, verbose_name='Es Flex')),
                ('flex_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Flex')),
                ('delivery_schedule', models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], default=None, max_length=5, null=True, verbose_name='Horario de entrega')),
                ('tracked', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bulk_upload_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envios.BulkLoadEnvios', verbose_name='ID de carga masiva')),
                ('carrier', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ID de carga masiva')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deposit', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Deposit', verbose_name='deposit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Town', verbose_name='Localidad de entrega')),
            ],
            options={
                'verbose_name': 'historical Envío',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBulkLoadEnvios',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('load_status', models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado')),
                ('csv_result', models.TextField(blank=True, default=None, null=True, verbose_name='Resultado')),
                ('errors', models.TextField(blank=True, default=None, null=True, verbose_name='Errores')),
                ('cells_to_paint', models.TextField(blank=True, default=None, null=True, verbose_name='Celdas que hay que pintar')),
                ('requires_manual_fix', models.BooleanField(default=False)),
                ('hashed_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hashed file')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Client', verbose_name='Usuario')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('deposit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Deposit', verbose_name='Depósito')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Carga masiva de envios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBolson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(blank=True, editable=False, verbose_name='creation datetime')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrier', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Bolsón',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('receiver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envios.Receiver')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('shipment_status', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado')),
                ('status_o', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado')),
                ('detail', models.CharField(default='0-1', max_length=2000, verbose_name='Detalle')),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Cargos al destinatario')),
                ('max_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha máxima de entrega')),
                ('is_flex', models.BooleanField(default=False, verbose_name='Es Flex')),
                ('flex_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Flex')),
                ('delivery_schedule', models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], default=None, max_length=5, null=True, verbose_name='Horario de entrega')),
                ('tracked', models.BooleanField(default=False)),
                ('bulk_upload_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.BulkLoadEnvios', verbose_name='ID de carga masiva')),
                ('carrier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier2', to=settings.AUTH_USER_MODEL, verbose_name='ID de carga masiva')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deposit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Deposit', verbose_name='deposit')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
            bases=('envios.receiver',),
        ),
        migrations.CreateModel(
            name='TrackingMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='movement action')),
                ('result', models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name="action's date time")),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_carrier', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_created_by', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('deposit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Deposit', verbose_name='deposit')),
                ('envios', models.ManyToManyField(to='envios.Envio', verbose_name='Envios relacionados')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Bolson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('carrier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('envios', models.ManyToManyField(to='envios.Envio')),
            ],
            options={
                'verbose_name': 'Bolsón',
                'verbose_name_plural': 'Bolsones',
            },
        ),
    ]
