# Generated by Django 2.2.2 on 2022-01-14 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('deposit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Domicilio de entrega')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de entrega')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. Postal de entrega')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Town', verbose_name='Localidad de entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envios.Destination')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre destinatario')),
                ('doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI destinatario')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono destinatario')),
            ],
            bases=('envios.destination',),
        ),
        migrations.CreateModel(
            name='BulkLoadEnvios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('load_status', models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado')),
                ('csv_result', models.TextField(blank=True, default=None, null=True, verbose_name='Resultado')),
                ('errors', models.TextField(blank=True, default=None, null=True, verbose_name='Errores')),
                ('cells_to_paint', models.TextField(blank=True, default=None, null=True, verbose_name='Celdas que hay que pintar')),
                ('requires_manual_fix', models.BooleanField(default=False)),
                ('hashed_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hashed file')),
                ('envios_were_created', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client', verbose_name='Usuario')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.Deposit', verbose_name='Depósito')),
            ],
            options={
                'verbose_name': 'Carga masiva de envios',
                'verbose_name_plural': 'Cargas masivas de envios',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('receiver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envios.Receiver')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('status', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado')),
                ('detail', models.CharField(default='0-1', max_length=200, verbose_name='Detalle')),
                ('charge', models.IntegerField(blank=True, null=True, verbose_name='Cargos al destinatario')),
                ('max_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha máxima de entrega')),
                ('is_flex', models.BooleanField(default=False, verbose_name='Es Flex')),
                ('flex_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Flex')),
                ('delivery_schedule', models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], default=None, max_length=5, null=True, verbose_name='Horario de entrega')),
                ('date_delivered', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de entrega')),
                ('tracked', models.BooleanField(default=False)),
                ('bulk_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.BulkLoadEnvios', verbose_name='ID de carga masiva')),
                ('carrier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Carrier', to=settings.AUTH_USER_MODEL, verbose_name='Portador')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente')),
                ('deposit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.Deposit', verbose_name='Depósito')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Editor', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
            bases=('envios.receiver',),
        ),
    ]
