# Generated by Django 2.2.2 on 2021-12-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='Subprueba',
        ),
    ]
