# Generated by Django 2.2.2 on 2022-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualización'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='date_updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualización'),
        ),
    ]
