# Generated by Django 2.2.2 on 2022-01-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='bulk_upload_id',
            new_name='bulk_upload',
        ),
        migrations.RenameField(
            model_name='historicalenvio',
            old_name='bulk_upload_id',
            new_name='bulk_upload',
        ),
        migrations.AddField(
            model_name='bulkloadenvios',
            name='envios_were_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbulkloadenvios',
            name='envios_were_created',
            field=models.BooleanField(default=False),
        ),
    ]
