# Generated by Django 2.2.2 on 2021-12-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='status_o',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='historicalenvio',
            old_name='status_o',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='envio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado Viejo'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado Viejo'),
        ),
    ]
