# Generated by Django 2.2.2 on 2021-09-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='register',
            new_name='author',
        ),
    ]
