# Generated by Django 2.2.2 on 2022-01-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-date_created'], 'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
    ]
