# Generated by Django 2.2.2 on 2021-12-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_auto_20211222_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='shipment_status',
        ),
        migrations.RemoveField(
            model_name='historicalenvio',
            name='shipment_status',
        ),
    ]
