# Generated by Django 2.2.2 on 2021-09-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_auto_20210922_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='author',
            new_name='created_by',
        ),
    ]
