# Generated by Django 2.2.2 on 2021-11-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_auto_20211119_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='deposit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.Deposit', verbose_name='deposit'),
        ),
        migrations.AddField(
            model_name='historicalenvio',
            name='deposit',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envios.Deposit', verbose_name='deposit'),
        ),
    ]
