# Generated by Django 2.2.2 on 2022-01-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_auto_20220104_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbolson',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='historicalbolson',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Bolson',
        ),
        migrations.DeleteModel(
            name='HistoricalBolson',
        ),
    ]
