# Generated by Django 2.2.2 on 2021-12-29 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envios', '0002_auto_20211229_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalenvio',
            old_name='created_by',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='created_by',
        ),
        migrations.AddField(
            model_name='envio',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Editor', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
