# Generated by Django 2.2.2 on 2022-01-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_auto_20220107_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='date_delivered',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='historicalenvio',
            name='date_delivered',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='detail',
            field=models.CharField(default='0-1', max_length=200, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='detail',
            field=models.CharField(default='0-1', max_length=200, verbose_name='Detalle'),
        ),
    ]
