# Generated by Django 2.2.2 on 2021-11-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_auto_20211119_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingmovement',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_carrier', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_created_by', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
