# Generated by Django 2.2.2 on 2021-12-29 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_auto_20211229_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Editor', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
    ]
