# Generated by Django 2.2.2 on 2021-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_auto_20210922_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='recipient_address',
            field=models.CharField(max_length=100, verbose_name="recipient's address"),
        ),
    ]
