# Generated by Django 2.2.2 on 2021-12-22 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_auto_20211222_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='carrier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Carrier', to=settings.AUTH_USER_MODEL, verbose_name='ID de carga masiva'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
