# Generated by Django 2.2.2 on 2021-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_auto_20211119_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalenvio',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
