# Generated by Django 2.2.2 on 2021-09-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_auto_20210928_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='detail',
            field=models.CharField(default='0-1', max_length=2000, verbose_name='detail'),
        ),
    ]
