# Generated by Django 2.2.2 on 2022-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_envio_deliverer'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking ID'),
        ),
    ]
