# Generated by Django 2.2.2 on 2021-12-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_auto_20211222_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='carrier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Carrier', to=settings.AUTH_USER_MODEL, verbose_name='Portador'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='deposit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Deposit', verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Portador'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='deposit',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Deposit', verbose_name='Depósito'),
        ),
    ]
