# Generated by Django 2.2.2 on 2021-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_auto_20210928_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('V', 'Viajando'), ('E', 'Entregado')], default='N', max_length=2, verbose_name='status'),
        ),
    ]
