# Generated by Django 2.2.2 on 2021-11-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_auto_20211119_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='is_ours',
            new_name='central',
        ),
        migrations.RenameField(
            model_name='historicaldeposit',
            old_name='is_ours',
            new_name='central',
        ),
    ]
