# Generated by Django 2.2.2 on 2022-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0006_auto_20220204_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='tracking_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Tracking ID'),
        ),
    ]
