# Generated by Django 2.2.2 on 2022-02-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0007_auto_20220204_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='floor_apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Piso/Departamento'),
        ),
    ]
