# Generated by Django 2.2.2 on 2021-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0007_historicalbolson_historicaldeposit_historicalenvio_historicaltrackingmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='status',
            new_name='shipment_status',
        ),
        migrations.RemoveField(
            model_name='historicalenvio',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalenvio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('V', 'Viajando'), ('E', 'Entregado')], default='N', max_length=2, verbose_name='status'),
        ),
    ]
