# Generated by Django 2.2.2 on 2021-10-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0008_auto_20211021_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEnvio',
        ),
    ]
