# Generated by Django 2.2.2 on 2022-02-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0008_destination_floor_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='receiver_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del destinatario'),
        ),
    ]
