# Generated by Django 2.2.2 on 2021-10-21 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_historicalclient'),
        ('places', '0010_historicalpartido_historicaltown_historicalzone'),
        ('envios', '0009_delete_historicalenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEnvio',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='date joined')),
                ('shipment_status', models.CharField(choices=[('N', 'Nuevo'), ('V', 'Viajando'), ('E', 'Entregado')], default='N', max_length=2, verbose_name='status')),
                ('detail', models.CharField(default='0-1', max_length=2000, verbose_name='detail')),
                ('recipient_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="recipient's name")),
                ('recipient_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name="recipient's doc id")),
                ('recipient_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name="recipient's phone num")),
                ('recipient_address', models.CharField(max_length=100, verbose_name="recipient's address")),
                ('recipient_entrances', models.CharField(blank=True, max_length=100, null=True, verbose_name="recipient's entrances")),
                ('recipient_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name="recipient's zip code")),
                ('recipient_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name="recipient's charge")),
                ('max_delivery_date', models.DateField(blank=True, null=True, verbose_name='max delivery date')),
                ('is_flex', models.BooleanField(default=False, verbose_name='Is Flex')),
                ('flex_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='flex id')),
                ('delivery_schedule', models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], max_length=5, null=True, verbose_name='delivery schedule')),
                ('qr_code', models.TextField(blank=True, max_length=60, null=True, verbose_name='generated qr code')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Town', verbose_name="recipient's town")),
            ],
            options={
                'verbose_name': 'historical Envío',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
