# Generated by Django 2.2.2 on 2022-02-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0009_envio_receiver_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado'), ('R', 'Devuelto')], default='N', max_length=2, verbose_name='Estado'),
        ),
    ]
