# Generated by Django 2.2.2 on 2021-10-21 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import envios.models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0010_historicalenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='delivery_schedule',
            field=models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], max_length=5, null=True, verbose_name='Horario de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='detail',
            field=models.CharField(default='0-1', max_length=2000, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='flex_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Flex'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='is_flex',
            field=models.BooleanField(default=False, verbose_name='Es Flex'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='max_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha máxima de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='qr_code',
            field=models.FileField(blank=True, max_length=60, null=True, upload_to=envios.models.upload_location, verbose_name='Código QR generado'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_address',
            field=models.CharField(max_length=100, verbose_name='Domicilio de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Cargos al destinatario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI destinatario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_entrances',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre destinatario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono destinatario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Town', verbose_name='Localidad de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='recipient_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. Postal de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='delivery_schedule',
            field=models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], max_length=5, null=True, verbose_name='Horario de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='detail',
            field=models.CharField(default='0-1', max_length=2000, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='flex_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Flex'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='is_flex',
            field=models.BooleanField(default=False, verbose_name='Es Flex'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='max_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha máxima de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='qr_code',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Código QR generado'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_address',
            field=models.CharField(max_length=100, verbose_name='Domicilio de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Cargos al destinatario'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI destinatario'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_entrances',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre destinatario'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono destinatario'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_town',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='places.Town', verbose_name='Localidad de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cod. Postal de entrega'),
        ),
    ]
