# Generated by Django 2.2.2 on 2022-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0010_auto_20220224_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado'), ('R', 'Devuelto'), ('C', 'Cancelado')], default='N', max_length=2, verbose_name='Estado'),
        ),
    ]
