# Generated by Django 2.2.2 on 2022-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0011_auto_20220309_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='flex_id',
            field=models.CharField(blank=True, max_length=50, null=True,
                                   unique=True, verbose_name='ID de Flex'),
        ),
    ]
