# Generated by Django 2.2.2 on 2021-10-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0011_auto_20211021_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('V', 'Viajando'), ('E', 'Entregado')], default='N', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('V', 'Viajando'), ('E', 'Entregado')], default='N', max_length=2, verbose_name='Estado'),
        ),
    ]
