# Generated by Django 2.2.2 on 2022-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0012_auto_20220406_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='unused_flex_ids',
            field=models.TextField(blank=True, null=True, verbose_name='IDs de Flex no usados'),
        ),
    ]
