# Generated by Django 2.2.2 on 2021-10-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0012_auto_20211021_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='recipient_entrances',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='recipient_entrances',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de entrega'),
        ),
    ]
