# Generated by Django 2.2.2 on 2022-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0013_envio_unused_flex_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='unused_flex_ids',
        ),
        migrations.AddField(
            model_name='bulkloadenvios',
            name='unused_flex_ids',
            field=models.TextField(blank=True, null=True, verbose_name='IDs de Flex no usados'),
        ),
    ]
