# Generated by Django 2.2.2 on 2021-10-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0015_auto_20211022_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostalCode',
        ),
    ]
