# Generated by Django 2.2.2 on 2022-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0015_auto_20220406_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='flex_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Flex'),
        ),
    ]
