# Generated by Django 2.2.2 on 2022-07-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0016_auto_20220407_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='has_delivery_attempt',
            field=models.BooleanField(default=False, verbose_name='Se ha intentado entregar'),
        ),
    ]
