# Generated by Django 2.2.2 on 2021-10-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0017_auto_20211025_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkloadenvios',
            options={'verbose_name': 'Carga masiva de envios', 'verbose_name_plural': 'Cargas masivas de envios'},
        ),
        migrations.AlterModelOptions(
            name='historicalbulkloadenvios',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Carga masiva de envios'},
        ),
        migrations.RemoveField(
            model_name='bulkloadenvios',
            name='file',
        ),
        migrations.RemoveField(
            model_name='historicalbulkloadenvios',
            name='file',
        ),
        migrations.AddField(
            model_name='bulkloadenvios',
            name='csv_result',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='bulkloadenvios',
            name='errors',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Errores'),
        ),
        migrations.AddField(
            model_name='bulkloadenvios',
            name='has_to_fix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkloadenvios',
            name='hashed_file',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Hashed file'),
        ),
        migrations.AddField(
            model_name='historicalbulkloadenvios',
            name='csv_result',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='historicalbulkloadenvios',
            name='errors',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Errores'),
        ),
        migrations.AddField(
            model_name='historicalbulkloadenvios',
            name='has_to_fix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbulkloadenvios',
            name='hashed_file',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Hashed file'),
        ),
        migrations.AlterField(
            model_name='bulkloadenvios',
            name='load_status',
            field=models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalbulkloadenvios',
            name='load_status',
            field=models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
