# Generated by Django 2.2.2 on 2021-10-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0018_auto_20211026_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkloadenvios',
            old_name='has_to_fix',
            new_name='requires_manual_fix',
        ),
        migrations.RenameField(
            model_name='historicalbulkloadenvios',
            old_name='has_to_fix',
            new_name='requires_manual_fix',
        ),
        migrations.AlterField(
            model_name='bulkloadenvios',
            name='load_status',
            field=models.CharField(choices=[(0, 'Done'), (1, 'Loading'), (2, 'Failed')], default=1, max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalbulkloadenvios',
            name='load_status',
            field=models.CharField(choices=[(0, 'Done'), (1, 'Loading'), (2, 'Failed')], default=1, max_length=1, verbose_name='Estado'),
        ),
    ]
