# Generated by Django 2.2.2 on 2021-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0019_auto_20211026_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkloadenvios',
            name='cells_to_paint',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Celdas que hay que pintar'),
        ),
        migrations.AddField(
            model_name='historicalbulkloadenvios',
            name='cells_to_paint',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Celdas que hay que pintar'),
        ),
    ]
