# Generated by Django 2.2.2 on 2021-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0020_auto_20211026_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkloadenvios',
            name='hashed_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hashed file'),
        ),
        migrations.AlterField(
            model_name='historicalbulkloadenvios',
            name='hashed_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hashed file'),
        ),
    ]
