# Generated by Django 2.2.2 on 2021-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0021_auto_20211026_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkloadenvios',
            name='load_status',
            field=models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalbulkloadenvios',
            name='load_status',
            field=models.CharField(choices=[('0', 'Done'), ('1', 'Loading'), ('2', 'Failed')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
