# Generated by Django 2.2.2 on 2021-10-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0022_auto_20211026_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='bulk_upload_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.BulkLoadEnvios', verbose_name='ID de carga masiva'),
        ),
        migrations.AddField(
            model_name='historicalenvio',
            name='bulk_upload_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envios.BulkLoadEnvios', verbose_name='ID de carga masiva'),
        ),
    ]
