# Generated by Django 2.2.2 on 2021-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0023_auto_20211028_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='action',
            field=models.CharField(choices=[('CS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('IE', 'Intento de entrega')], default='CS', max_length=50, verbose_name='movement action'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='action',
            field=models.CharField(choices=[('CS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('IE', 'Intento de entrega')], default='CS', max_length=50, verbose_name='movement action'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result'),
        ),
    ]
