# Generated by Django 2.2.2 on 2021-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0024_auto_20211028_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='action',
            field=models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='movement action'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='action',
            field=models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='movement action'),
        ),
    ]
