# Generated by Django 2.2.2 on 2021-10-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0025_auto_20211028_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingmovement',
            name='bolsones',
        ),
        migrations.RemoveField(
            model_name='trackingmovement',
            name='envios',
        ),
        migrations.AddField(
            model_name='historicaltrackingmovement',
            name='envio',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envios.Envio', verbose_name='Envio relacionado'),
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='envio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.Envio', verbose_name='Envio relacionado'),
        ),
    ]
