# Generated by Django 2.2.2 on 2021-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0026_auto_20211028_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result'),
        ),
    ]
