# Generated by Django 2.2.2 on 2021-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0027_auto_20211028_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='shipment_status',
            field=models.CharField(choices=[('N', 'Nuevo'), ('M', 'Viajando'), ('S', 'En depósito'), ('D', 'Entregado')], default='N', max_length=2, verbose_name='Estado'),
        ),
    ]
