# Generated by Django 2.2.2 on 2021-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0028_auto_20211029_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltrackingmovement',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='trackingmovement',
            name='envio',
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='envios',
            field=models.ManyToManyField(to='envios.Envio', verbose_name='Envios relacionados'),
        ),
    ]
