# Generated by Django 2.2.2 on 2021-11-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0029_auto_20211030_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingmovement',
            old_name='date_time',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='historicaltrackingmovement',
            name='date_time',
        ),
        migrations.AddField(
            model_name='historicaltrackingmovement',
            name='date_created',
            field=models.DateTimeField(blank=True, default=None, editable=False, verbose_name="action's date time"),
            preserve_default=False,
        ),
    ]
