# Generated by Django 2.2.2 on 2021-11-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20211102_1715'),
        ('envios', '0030_auto_20211101_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldeposit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicaldeposit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldeposit',
            name='town',
        ),
        migrations.AddField(
            model_name='envio',
            name='deposit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Deposit', verbose_name='Depósito actual'),
        ),
        migrations.AddField(
            model_name='historicalenvio',
            name='deposit',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Deposit', verbose_name='Depósito actual'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='delivery_schedule',
            field=models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], default=None, max_length=5, null=True, verbose_name='Horario de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalenvio',
            name='delivery_schedule',
            field=models.CharField(blank=True, choices=[('07-10', '7 a 10 h'), ('10-13', '10 a 13 h'), ('13-16', '13 a 16 h'), ('16+', '+16 h')], default=None, max_length=5, null=True, verbose_name='Horario de entrega'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='deposit',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.Deposit', verbose_name='deposit'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='deposit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Deposit', verbose_name='deposit'),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='HistoricalDeposit',
        ),
    ]
