# Generated by Django 2.2.2 on 2021-11-02 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envios', '0032_auto_20211102_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltrackingmovement',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='trackingmovement',
            name='user',
        ),
        migrations.AddField(
            model_name='historicaltrackingmovement',
            name='carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user responsible'),
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier', to=settings.AUTH_USER_MODEL, verbose_name='user responsible'),
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='user responsible'),
        ),
    ]
