# Generated by Django 2.2.2 on 2021-11-02 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0033_auto_20211102_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='movement result'),
        ),
    ]
