# Generated by Django 2.2.2 on 2021-11-03 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0034_auto_20211102_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='bulk_upload_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.BulkLoadEnvios', verbose_name='ID de carga masiva'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package'),
        ),
    ]
