# Generated by Django 2.2.2 on 2022-03-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('0', 'Administrativo'), ('1', 'Alquiler'), ('2', 'Compras'), ('3', 'Facturacion'), ('4', 'Impuestos'), ('5', 'Insumos'), ('6', 'Mantenimiento'), ('7', 'Publicidad'), ('8', 'Seguros'), ('9', 'Servicios'), ('10', 'Sueldos'), ('11', 'Otros')], max_length=2, verbose_name='Categoría'),
        ),
    ]
