# Generated by Django 2.2.2 on 2022-01-13 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
