# Generated by Django 2.2.2 on 2022-01-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_hash_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='hash_sum',
        ),
    ]
