# Generated by Django 2.2.2 on 2022-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220411_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('0', 'Administrativo'), ('1', 'Alquiler'), ('12', 'Cobro por cuenta y orden de terceros'), ('2', 'Compras'), ('3', 'Facturacion'), ('4', 'Impuestos'), ('5', 'Insumos'), ('6', 'Mantenimiento'), ('14', 'Pagos'), ('7', 'Publicidad'), ('13', 'Retiros de caja en efectivo'), ('8', 'Seguros'), ('9', 'Servicios'), ('10', 'Sueldos'), ('11', 'Otros')], max_length=2, verbose_name='Categoría'),
        ),
    ]
