# Generated by Django 2.2.2 on 2022-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_hash_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash_sum',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
    ]
