# Generated by Django 2.2.2 on 2022-01-26 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='client',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='employee',
        ),
        migrations.CreateModel(
            name='EmployeeSummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='summaries.Summary')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Resumen de empleado',
                'verbose_name_plural': 'Resúmenes de empleado',
                'ordering': ['-date_created'],
            },
            bases=('summaries.summary',),
        ),
        migrations.CreateModel(
            name='ClientSummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='summaries.Summary')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Resumen de cliente',
                'verbose_name_plural': 'Resúmenes de cliente',
                'ordering': ['-date_created'],
            },
            bases=('summaries.summary',),
        ),
    ]
