# Generated by Django 2.2.2 on 2022-01-27 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_auto_20220126_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsummary',
            options={'ordering': ['-date_created'], 'verbose_name': 'Resumen de cliente', 'verbose_name_plural': 'Resúmenes de clientes'},
        ),
        migrations.AlterModelOptions(
            name='employeesummary',
            options={'ordering': ['-date_created'], 'verbose_name': 'Resumen de empleado', 'verbose_name_plural': 'Resúmenes de empleados'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={},
        ),
        migrations.AlterField(
            model_name='clientsummary',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_summary', to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='employeesummary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_summary', to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
    ]
