# Generated by Django 2.2.2 on 2022-03-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
