# Generated by Django 2.2.2 on 2022-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_log_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
