# Generated by Django 2.2.2 on 2022-03-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_log_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(default='other', max_length=255),
            preserve_default=False,
        ),
    ]
