# Generated by Django 2.2.2 on 2022-03-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='type',
        ),
        migrations.AddField(
            model_name='log',
            name='_type',
            field=models.CharField(default='other', max_length=255),
        ),
    ]
