# Generated by Django 2.2.2 on 2022-04-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_change_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='labels',
            new_name='label',
        ),
    ]
