# Generated by Django 2.2.2 on 2022-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_auto_20220410_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='label',
            field=models.CharField(choices=[('IM', 'Mejora'), ('BF de error', 'Corrección de error'), ('UP', 'Actualización'), ('MC', 'Corrección menor'), ('WF', 'Sin solución')], default='IM', max_length=2),
        ),
    ]
