# Generated by Django 2.2.2 on 2022-04-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0005_auto_20220410_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-date_created'], 'verbose_name': 'Cambio', 'verbose_name_plural': 'Cambios'},
        ),
    ]
