# Generated by Django 2.2.2 on 2022-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0006_auto_20220418_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='label',
            field=models.CharField(choices=[('IM', 'Mejora'), ('BF', 'Corrección de error'), ('UP', 'Actualización'), ('MC', 'Corrección menor'), ('WF', 'Sin solución')], default='IM', max_length=2),
        ),
    ]
