# Generated by Django 2.2.2 on 2022-09-26 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changes', '0007_auto_20220605_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='users',
            field=models.ManyToManyField(related_name='Users_who_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='change',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Author', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
