# Generated by Django 2.2.2 on 2022-09-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0008_auto_20220926_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='users',
            new_name='readers',
        ),
    ]
