# Generated by Django 2.2.2 on 2022-09-26 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0009_auto_20220926_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='readers',
            field=models.ManyToManyField(blank=True, null=True, related_name='Users_who_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
