# Generated by Django 2.2.2 on 2022-09-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0010_auto_20220926_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-date_created'], 'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
    ]
