# Generated by Django 2.2.2 on 2022-01-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('name', models.CharField(default=None, max_length=50, unique=True, verbose_name='Nombre')),
                ('address', models.CharField(default=None, max_length=100, verbose_name='Dirección')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('is_sinergia', models.BooleanField(default=False, verbose_name='Es de sinergia?')),
                ('is_central', models.BooleanField(default=False, verbose_name='Es central?')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Town', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['name'],
            },
        ),
    ]
