# Generated by Django 2.2.2 on 2022-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='is_central',
            field=models.BooleanField(default=True, verbose_name='Es central?'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='is_sinergia',
            field=models.BooleanField(default=True, verbose_name='Es de sinergia?'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='is_central',
            field=models.BooleanField(default=True, verbose_name='Es central?'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='is_sinergia',
            field=models.BooleanField(default=True, verbose_name='Es de sinergia?'),
        ),
    ]
