# Generated by Django 2.2.2 on 2022-01-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['name'], 'verbose_name': 'Depósito', 'verbose_name_plural': 'Depósitos'},
        ),
    ]
