# Generated by Django 2.2.2 on 2022-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20220104_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='is_central',
            field=models.BooleanField(default=False, verbose_name='Es central?'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='is_sinergia',
            field=models.BooleanField(default=False, verbose_name='Es de sinergia?'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='is_central',
            field=models.BooleanField(default=False, verbose_name='Es central?'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='is_sinergia',
            field=models.BooleanField(default=False, verbose_name='Es de sinergia?'),
        ),
    ]
