# Generated by Django 2.2.2 on 2022-01-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_auto_20220105_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
