# Generated by Django 2.2.2 on 2022-01-12 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('priority', models.CharField(choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], default='2', max_length=1, verbose_name='Prioridad')),
                ('subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('msg', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('1', 'Enviado'), ('2', 'Abierto'), ('3', 'Cerrado')], default='1', max_length=1, verbose_name='Estado')),
                ('closed_reason', models.CharField(blank=True, choices=[('1', 'Cancelado'), ('2', 'Irrelevante'), ('3', 'Innecesario'), ('4', 'Resuelto'), ('5', 'Existe otro ticket similar'), ('6', 'No se pudo resolver')], default='6', max_length=1, null=True, verbose_name='Razón de cierre')),
                ('closed_msg', models.TextField(blank=True, null=True, verbose_name='Mensaje de cierre')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Creación')),
                ('priority', models.CharField(choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], default='2', max_length=1, verbose_name='Prioridad')),
                ('subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('msg', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('1', 'Enviado'), ('2', 'Abierto'), ('3', 'Cerrado')], default='1', max_length=1, verbose_name='Estado')),
                ('closed_reason', models.CharField(blank=True, choices=[('1', 'Cancelado'), ('2', 'Irrelevante'), ('3', 'Innecesario'), ('4', 'Resuelto'), ('5', 'Existe otro ticket similar'), ('6', 'No se pudo resolver')], default='6', max_length=1, null=True, verbose_name='Razón de cierre')),
                ('closed_msg', models.TextField(blank=True, null=True, verbose_name='Mensaje de cierre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ticket',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=tickets.models.upload_location, verbose_name='Attachment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket', verbose_name='Ticket')),
            ],
        ),
    ]
