# Generated by Django 2.2.2 on 2022-01-04 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('priority', models.CharField(choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], default='2', max_length=1, verbose_name='Prioridad')),
                ('subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('msg', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('1', 'Enviado'), ('2', 'Abierto'), ('3', 'Cerrado')], default='1', max_length=1, verbose_name='Estado')),
                ('closed_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón de cierre')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
