# Generated by Django 2.2.2 on 2022-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_historicalticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='closed_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de cierre'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de cierre'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='closed_reason',
            field=models.CharField(choices=[('1', 'Cancelado'), ('2', 'Irrelevante'), ('3', 'Innecesario'), ('4', 'Resuelto'), ('5', 'Existe otro ticket similar'), ('6', 'No se pudo resolver')], default='6', max_length=1, verbose_name='Razón de cierre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_reason',
            field=models.CharField(choices=[('1', 'Cancelado'), ('2', 'Irrelevante'), ('3', 'Innecesario'), ('4', 'Resuelto'), ('5', 'Existe otro ticket similar'), ('6', 'No se pudo resolver')], default='6', max_length=1, verbose_name='Razón de cierre'),
        ),
    ]
