# Generated by Django 2.2.2 on 2022-04-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['date_created'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
    ]
