# Generated by Django 2.2.2 on 2022-01-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20220104_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('1', 'Cancelado'), ('2', 'Irrelevante'), ('3', 'Innecesario'), ('4', 'Resuelto'), ('5', 'Existe otro ticket similar'), ('6', 'No se pudo resolver')], default='6', max_length=1, null=True, verbose_name='Razón de cierre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('1', 'Cancelado'), ('2', 'Irrelevante'), ('3', 'Innecesario'), ('4', 'Resuelto'), ('5', 'Existe otro ticket similar'), ('6', 'No se pudo resolver')], default='6', max_length=1, null=True, verbose_name='Razón de cierre'),
        ),
    ]
