# Generated by Django 2.2.2 on 2022-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20220411_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='canceled_reason',
            field=models.CharField(blank=True, choices=[('IR', 'Irrelevante'), ('IN', 'Innecesario'), ('RE', 'Resuelto'), ('TS', 'Existe otro ticket similar')], max_length=2, null=True, verbose_name='Razón de cancelación'),
        ),
    ]
