# Generated by Django 2.2.2 on 2022-04-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_canceled_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='canceled_reason',
        ),
    ]
