# Generated by Django 2.2.2 on 2022-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20220411_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_priority_update',
            field=models.BooleanField(default=False, verbose_name='Actualización de prioridad'),
        ),
    ]
