# Generated by Django 2.2.2 on 2022-01-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_file_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Attachment',
        ),
    ]
