# Generated by Django 2.2.2 on 2022-07-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketmessage_is_priority_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-date_created'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
    ]
