# Generated by Django 2.2.2 on 2022-07-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20220717_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['date_created'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
    ]
