# Generated by Django 2.2.2 on 2022-12-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20220717_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('msg', models.TextField(blank=True, default='', null=True, verbose_name='Message')),
                ('function_name', models.TextField(blank=True, default=True, null=True, verbose_name='Function name')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Ticket', verbose_name='Ticket')),
                ('ticket_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.TicketMessage', verbose_name='TicketMessage')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['date_created'],
            },
        ),
    ]
