# Generated by Django 2.2.2 on 2022-01-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0001_initial'),
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='Acción')),
                ('result', models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='Resultado')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Comentario')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name="action's date time")),
                ('proof', models.FileField(blank=True, null=True, upload_to=tracking.models.upload_location, verbose_name='archivo probatorio')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_carrier', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_created_by', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('deposit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.Deposit', verbose_name='deposit')),
                ('envios', models.ManyToManyField(to='envios.Envio', verbose_name='Envios relacionados')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTrackingMovement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('action', models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='Acción')),
                ('result', models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='Resultado')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Comentario')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name="action's date time")),
                ('proof', models.TextField(blank=True, max_length=100, null=True, verbose_name='archivo probatorio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user carrying package')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('deposit', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deposit.Deposit', verbose_name='deposit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Movimiento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
