# Generated by Django 2.2.2 on 2021-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='action',
            field=models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='action',
            field=models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega')], default='AS', max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('custom', 'Otro')], default='_new', max_length=50, verbose_name='Resultado'),
        ),
    ]
