# Generated by Django 2.2.2 on 2022-01-24 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmovement',
            name='label',
            field=models.CharField(blank=True, choices=[('all', 'Todos'), ('by_envios_ids', 'By envíos'), ('by_towns_ids', 'By towns'), ('by_partidos_ids', 'By partidos'), ('by_zones_ids', 'By zonas')], default='all', max_length=15, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='from_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_carrier', to=settings.AUTH_USER_MODEL, verbose_name='El usuario que transportó el/los paquete/s (FROM)'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='from_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_deposit', to='deposit.Deposit', verbose_name='El depósito que tenía el/los paquete/s (FROM)'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='to_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_carrier', to=settings.AUTH_USER_MODEL, verbose_name='El usuario que tiene el/los paquete/s (TO)'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='to_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_deposit', to='deposit.Deposit', verbose_name='El depósito que tiene el/los paquete/s (TO)'),
        ),
    ]
