# Generated by Django 2.2.2 on 2022-01-20 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0003_auto_20220117_1942'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmovement',
            name='from_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_carrier', to=settings.AUTH_USER_MODEL, verbose_name='user which was carrying package(s)'),
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='from_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_deposit', to='deposit.Deposit', verbose_name='deposit which was holding package(s)'),
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='to_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_carrier', to=settings.AUTH_USER_MODEL, verbose_name='user which is carrying package(s)'),
        ),
        migrations.AddField(
            model_name='trackingmovement',
            name='to_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_deposit', to='deposit.Deposit', verbose_name='deposit which is holding package(s)'),
        ),
    ]
