# Generated by Django 2.2.2 on 2022-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20220124_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingmovement',
            name='action',
            field=models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega'), ('TR', 'Transferencia')], default='AS', max_length=50, verbose_name='Acción'),
        ),
    ]
