# Generated by Django 2.2.2 on 2022-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20220301_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingmovement',
            name='label',
            field=models.CharField(blank=True, choices=[('all', 'Todos'), ('by_envios_ids', 'por envíos'), ('by_towns_ids', 'por localidades'), ('by_partidos_ids', 'por partidos'), ('by_zones_ids', 'por zonas')], default='all', max_length=15, null=True, verbose_name='Label'),
        ),
    ]
