# Generated by Django 2.2.2 on 2022-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20220306_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmovement',
            name='receiver_doc_id',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Documento de quien recibió'),
        ),
    ]
