# Generated by Django 2.2.2 on 2022-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_trackingmovement_receiver_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingmovement',
            name='action',
            field=models.CharField(choices=[('AS', 'Carga en sistema'), ('RC', 'Recolección'), ('DP', 'Depósito'), ('DA', 'Intento de entrega'), ('TR', 'Transferencia'), ('RE', 'Devolución'), ('C', 'Cancelación')], default='AS', max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='trackingmovement',
            name='result',
            field=models.CharField(choices=[('_new', 'Agregado al sistema'), ('in_deposit', 'En depósito'), ('success', 'Entrega exitosa'), ('rejected', 'Rechazado en lugar de destino'), ('reprogram', 'Reprogramado'), ('not-respond', 'Sin respuesta'), ('transfered', 'Transferido'), ('collected', 'Recolectado'), ('custom', 'Otro'), ('returned', 'Devuelto'), ('canceled', 'Cancelado')], default='_new', max_length=50, verbose_name='Resultado'),
        ),
    ]
