# Generated by Django 2.2.2 on 2022-09-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20220402_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingmovement',
            options={'ordering': ['-date_created'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
    ]
