# Generated by Django 2.2.2 on 2022-01-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('province', models.CharField(choices=[('BA', 'Buenos Aires'), ('CAB', 'CABA'), ('CA', 'Catamarca'), ('CH', 'Chaco'), ('CT', 'Chubut'), ('CR', 'Corrientes'), ('CB', 'Córdoba'), ('ER', 'Entre Ríos'), ('FO', 'Formosa'), ('JY', 'Jujuy'), ('LP', 'La Pampa'), ('LR', 'La Rioja'), ('MZ', 'Mendoza'), ('MI', 'Misiones'), ('NQN', 'Neuquén'), ('RN', 'Río Negro'), ('SA', 'Salta'), ('SJ', 'San Juan'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SE', 'Santiago del Estero'), ('TF', 'Tierra del Fuego...'), ('TU', 'Tucumán')], default='BA', max_length=3, verbose_name='Province')),
                ('is_amba', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delivery_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.DeliveryCode', verbose_name='Delivery code')),
                ('flex_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.FlexCode', verbose_name='Flex code')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Partido', verbose_name='Partido')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('asigned_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignet_to', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('code', models.CharField(default=None, max_length=10, verbose_name='Numero')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('towns', models.ManyToManyField(blank=True, default=None, to='places.Town', verbose_name='Localidades')),
            ],
            options={
                'verbose_name': 'Código Postal',
                'verbose_name_plural': 'Códigos Postales',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Zone'),
        ),
    ]
