# Generated by Django 2.2.2 on 2021-09-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='province',
            field=models.CharField(choices=[('BA', 'Buenos Aaires'), ('CAB', 'CABA'), ('CA', 'Catamarca'), ('CH', 'Chaco'), ('CT', 'Chubut'), ('CR', 'Corrientes'), ('CB', 'Córdoba'), ('ER', 'Entre Ríos'), ('FO', 'Formosa'), ('JY', 'Jujuy'), ('LP', 'La Pampa'), ('LR', 'La Rioja'), ('MZ', 'Mendoza'), ('MI', 'Misiones'), ('NQN', 'Neuquén'), ('RN', 'Río Negro'), ('SA', 'Salta'), ('SJ', 'San Juan'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SE', 'Santiago del Estero'), ('TF', 'Tierra del Fuego...'), ('TU', 'Tucumán')], default='BA', max_length=3, verbose_name='Province'),
        ),
    ]
