# Generated by Django 2.2.2 on 2022-01-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['name'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['name'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
    ]
