# Generated by Django 2.2.2 on 2021-12-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicaldeposit',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=50, verbose_name='Nombre'),
        ),
    ]
