# Generated by Django 2.2.2 on 2021-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210922_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='is_amba',
            field=models.BooleanField(default=False),
        ),
    ]
