# Generated by Django 2.2.2 on 2022-01-27 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220124_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='town',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='province',
            field=models.CharField(choices=[('BA', 'Buenos Aires'), ('CAB', 'CABA'), ('CA', 'Catamarca'), ('CH', 'Chaco'), ('CT', 'Chubut'), ('CR', 'Corrientes'), ('CB', 'Córdoba'), ('ER', 'Entre Ríos'), ('FO', 'Formosa'), ('JY', 'Jujuy'), ('LP', 'La Pampa'), ('LR', 'La Rioja'), ('MZ', 'Mendoza'), ('MI', 'Misiones'), ('NQN', 'Neuquén'), ('RN', 'Río Negro'), ('SA', 'Salta'), ('SJ', 'San Juan'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SE', 'Santiago del Estero'), ('TF', 'Tierra del Fuego'), ('TU', 'Tucumán')], default='BA', max_length=3, verbose_name='Province'),
        ),
    ]
