# Generated by Django 2.2.2 on 2022-03-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220127_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Zone', verbose_name='Zona'),
        ),
    ]
