# Generated by Django 2.2.2 on 2021-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20211009_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='wiki_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wikipedia Page'),
        ),
    ]
