# Generated by Django 2.2.2 on 2021-10-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_town_wiki_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='asigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignet_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
