# Generated by Django 2.2.2 on 2021-10-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20211012_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='wiki_url',
        ),
    ]
