# Generated by Django 2.2.2 on 2021-10-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_town_wiki_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='amba_zone',
            new_name='zone',
        ),
    ]
