# Generated by Django 2.2.2 on 2021-10-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_postalcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postalcode',
            old_name='publications',
            new_name='towns',
        ),
    ]
