# Generated by Django 2.2.2 on 2021-10-22 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0012_auto_20211022_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostalCode',
            new_name='ZipCode',
        ),
    ]
