# Generated by Django 2.2.2 on 2021-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20211022_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='towns',
        ),
        migrations.AddField(
            model_name='town',
            name='zip_codes',
            field=models.ManyToManyField(to='places.ZipCode'),
        ),
    ]
