# Generated by Django 2.2.2 on 2021-10-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20211024_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name': 'Código Postal', 'verbose_name_plural': 'Código Postal'},
        ),
    ]
