# Generated by Django 2.2.2 on 2021-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20211024_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='zip_codes',
            field=models.ManyToManyField(blank=True, null=True, to='places.ZipCode'),
        ),
    ]
