# Generated by Django 2.2.2 on 2021-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20211025_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='zip_codes',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='towns',
            field=models.ManyToManyField(blank=True, null=True, to='places.Town'),
        ),
    ]
