# Generated by Django 2.2.2 on 2021-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20211025_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='towns',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='places.Town', verbose_name='Localidades'),
        ),
    ]
